version: '3.9'
services:
    nginx:
        image: nginx:latest
        container_name: ${APP_NAME}-nginx
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./dist:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm

    php-fpm:
        image: php:8.2-fpm
        container_name: ${APP_NAME}-php
        volumes:
            - ./dist:/var/www/html
        links:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: ${APP_NAME}-mysql
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${APP_NAME}-phpmyadmin
        environment:
            PMA_HOST: "${DB_HOST}"
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
        ports:
            - '8080:80'
        links:
            - mysql:mysql